name: demo contineous integration 
on:
   push:
      branches:
         - main
jobs:
   build:
      runs-on: windows-latest

      steps:
         - name: Checkout to repository
           uses: action/checkout@v3
           
      
         - name: Download the setup jdk
           uses: action/setup-java@v3
           with:
              java-version: '21'
              distributor: 'temurin'
           continue-on-error: true
         - name: Downoad and Setup Maven
           uses: stCarolas/setup-maven@v4.4
           with:
              maven-version: 3.2.2
         - name: build using maven
           run: mvn clean install
           
       # steps:
       #   - name:  Run-Test
       #     run:  mvn test -D"cucumber.filter.tags=@ui"
       #     env:
       #      Display:  :19
       #      CUCUMBER_PUBLISH_TOKEN:  d63d365a-79c0-4dd8-b216-2277ba15d362
       #      continue-on-error:  true
       #  - uses:  actions/upload-artifact@v3
       #    if: always()
       #    with:
       #        name: Report
       #        path: test-output
       #        retention-days:  30
         
           
